# Generated by Django 4.2.21 on 2025-05-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ErrorEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                (
                    "cause_overview",
                    models.TextField(
                        blank=True,
                        help_text="A general overview of common causes.",
                        null=True,
                    ),
                ),
                (
                    "solution_overview",
                    models.TextField(
                        blank=True,
                        help_text="A general overview of common solutions or steps.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="main_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Error Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
