# Generated by Django 4.2.21 on 2025-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="errorentry",
            options={
                "ordering": ["-updated_at"],
                "verbose_name_plural": "Error Entries",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=120, unique=True
            ),
        ),
        migrations.AddField(
            model_name="errorentry",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=280, unique=True
            ),
        ),
    ]
