# Generated by Django 4.2.21 on 2025-05-27 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0003_comment_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorentry",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_errors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
