# Generated by Django 4.2.21 on 2025-05-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0004_errorentry_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorentry",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Visible to all users if checked.",
            ),
        ),
        migrations.AddField(
            model_name="errorentry",
            name="moderator_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for moderators regarding this entry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="errorentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
